language: node_js
node_js:
  - "10"
env:
  global:
  - USER="valantonini"
  - EMAIL="val.antonini@gmail.com"
  - REPO="travisci-test"
  - GH_REPO="github.com/${USER}/${REPO}.git"
install:
  - npm install wintersmith -g
  - npm install gulp-cli -g
  - npm install
script:
  - gulp publish
after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git clone git://${GH_REPO} ../${REPO}
  - cd ../${REPO}
  - git rm -r *
  - git commit -m "removing old"
  - mv ../arakawa/build/* .
  - git remote rm origin
  - git remote add origin "https://${GH_TOKEN}@${GH_REPO}"
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git add --all
  - git fetch
  #- git commit --all -m ${MESSAGE}
  - git commit -m "updated"
  - git push "https://${GH_TOKEN}@${GH_REPO}" master > /dev/null 2>&1

  
