language: node_js
node_js:
  - "10"
env:
  global:
  - USER="valantonini"
  - EMAIL="val.antonini@mail.com"
  - REPO="travisci-test"
  - GH_REPO="github.com/${USER}/${REPO}.git"
install:
  - npm install wintersmith -g
  - npm install gulp-cli -g
  - npm install
script:
  - gulp publish
after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git clone git://${GH_REPO}
  - mv -f build/* ${REPO}
  - cd ${REPO}
  - git add *
  - git commit -a -m ${MESSAGE}
  - git push "https://${GH_TOKEN}@${GH_REPO}" master 

  