language: node_js
node_js:
  - "10"
env:
  global:
  - USER="valantonini"
  - EMAIL="val.antonini@gmail.com"
  - REPO="travisci-test"
  - GH_REPO="github.com/${USER}/${REPO}.git"
install:
  - npm install wintersmith -g
  - npm install gulp-cli -g
  - npm install
script:
  - gulp publish
after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git clone git://${GH_REPO} ../${REPO}
  - mv -f build/* ../${REPO}
  - cd ../${REPO}
  - git fetch
  - git config --global user.email ${EMAIL}
  - git config --global user.name ${USER}
  - git add --all
  - git commit -m ${MESSAGE}
  - git push "https://${GH_TOKEN}@${GH_REPO}" master > /dev/null 2>&1

  
