language: node_js
node_js:
  - "10"
env:
  global:
  - USER="valantonini"
  - EMAIL="${GH_EMAIL}"
  - REPO="valantonini.github.io"
  - GH_REPO="github.com/${USER}/${REPO}.git"
install:
  - npm install wintersmith -g
  - npm install gulp-cli -g
  - npm install
script:
  - gulp publish
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  local_dir: build
  repo: github.com/valantonini/valantonini.github.io
  target_branch: master
  fqdn: valantonini.com
  email: $GH_EMAIL
  name: val antonini
  on:
    branch: master

  
